CREATE SEQUENCE SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PERSON
(
  ID            BIGINT PRIMARY KEY                  NOT NULL
);

CREATE TABLE PERSON_ID_OVERWRITTEN
(
  ID            BIGINT PRIMARY KEY                  NOT NULL
);


INSERT INTO PERSON (ID)
VALUES (-1);

INSERT INTO PERSON (ID)
VALUES (-2);

INSERT INTO PERSON_ID_OVERWRITTEN (ID)
VALUES (-3);

INSERT INTO PERSON_ID_OVERWRITTEN (ID)
VALUES (-4);
